### ISSUE TITLE
`fetch': undefined method `force_encoding'

### ISSUE THREAD

**Issue by jaccorens** [joeyates/imap-backup#73]
I'm having troubles syncing one of my two Apple iCould accounts. One of the accounts syncs fine, but the other one fails with the following error:

D, [2019-06-12T07:33:58.479612 #19668] DEBUG -- : Running backup of account: myusername@mac.com
D, [2019-06-12T07:33:58.480138 #19668] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-06-12T07:33:59.311464 #19668] DEBUG -- : Logging in: myusername@mac.com/xxxxxxxxxxxxxxxxxxx
D, [2019-06-12T07:33:59.694268 #19668] DEBUG -- : Login complete
D, [2019-06-12T07:34:00.355061 #19668] DEBUG -- : [INBOX] running backup
D, [2019-06-12T07:34:01.817046 #19668] DEBUG -- : [INBOX] 44 new messages
/var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/folder.rb:64:in `fetch': undefined method `force_encoding' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/downloader.rb:16:in `block in run'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/downloader.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/downloader.rb:15:in `with_index'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/downloader.rb:15:in `run'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/connection.rb:53:in `block in run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/connection.rb:112:in `block in each_folder'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/connection.rb:109:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/connection.rb:109:in `each_folder'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/account/connection.rb:49:in `run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/configuration/list.rb:18:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/lib/imap/backup/configuration/list.rb:18:in `each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-2.1.0/bin/imap-backup:73:in `<top (required)>'
	from /usr/local/bin/imap-backup:22:in `load'
	from /usr/local/bin/imap-backup:22:in `<main>'

What can I do to help debug?

**Comment by joeyates** [comment]
It looks like the email data is coming back incomplete in that case.

This is fixed by 6622ba3d08e36a754488f95178dc917f429de5b3 where I've added a handler for this situation (it simply drops the message). It's released as v.2.1.1

**Comment by jaccorens** [comment]
This update does not seem to fix it for me;

```
root@athos:/home/admin# imap-backup -version
2.1.1
```

```
D, [2019-06-30T09:35:20.829567 #9493] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-06-30T09:35:21.743551 #9493] DEBUG -- : Logging in: username@mac.com/xxxxxxxxxxxxxxxxxxx
D, [2019-06-30T09:35:22.196431 #9493] DEBUG -- : Login complete
W, [2019-06-30T09:35:22.986383 #9493]  WARN -- : Unable to get folder list for account username@mac.com
W, [2019-06-30T09:35:22.986688 #9493]  WARN -- : Unable to get folder list
```

An 2nd iCloud account syncs fine, as well as two other map accounts on cyrusimap.

Is there an option to do a full verbose debug, so we can see where it get's stuck?
